### ISSUE TITLE
Fathom update consequences

### ISSUE THREAD

**Issue by ndeblauw** [beyondcode/fathom-analytics-api#3]
Today I noticed an error in Flare for this line (which previously worked fine for collecting the data)
![image](https://user-images.githubusercontent.com/4344869/123929168-de1da400-d98e-11eb-9c32-5477a73c985a.png)

![image](https://user-images.githubusercontent.com/4344869/123929206-e970cf80-d98e-11eb-8ddc-e83ad624cfb6.png)

I guess the root cause is the changes recently made at fathom, see https://usefathom.com/blog/new-fathom
I didn't have time yet to investigate or propose solution (sorry for that), just wanted to inform you

**Comment by austinginder** [comment]
I think the main issue has to do with a different name on the login submit button. Just submitted a pull request to resolve. https://github.com/beyondcode/fathom-analytics-api/pull/4

**Comment by tectonic-pg** [comment]
The change in @austinginder's PR works for me

**Comment by sschlein** [comment]
We've merged and released this in 1.1
