### ISSUE TITLE
Incompatible PHP version

### ISSUE THREAD

**Issue by theodorewilkins** [beyondcode/fathom-analytics-api#5]
`Package beyondcode/fathom-api has a PHP requirement incompatible with your   
  PHP version..`

Is it possible to push the PHP requirement up to version 8.0.3?

**Comment by sschlein** [comment]
Fathom is releasing their official API within the next days and this means that we'll deprecate this unofficial package. If you rely on this package, I recommend forking it and changing the requirement to your needs.

**Comment by theodorewilkins** [comment]
Thank you @sschlein 👍
